# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r


language: R
r:
  - release
  - devel
sudo: false
cache: packages

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.9

before_install:
  mkdir ~/.R && echo "CXX=g++-4.9" > ~/.R/Makevars
