// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// fasta_wf
Rcpp::DataFrame fasta_wf(int k, const char* file);
RcppExport SEXP zwc_fasta_wf(SEXP kSEXP, SEXP fileSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< const char* >::type file(fileSEXP);
    rcpp_result_gen = Rcpp::wrap(fasta_wf(k, file));
    return rcpp_result_gen;
END_RCPP
}
