# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Count words in fasta file
#'
#' @param k    Integer expressing word size
#' @param file Fasta filename
#' @export
fasta_wf <- function(k, file) {
    .Call('zwc_fasta_wf', PACKAGE = 'zwc', k, file)
}

