# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Count words in fasta character array
#'
#' @param k    Integer expressing word size
#' @param text A character array holding all fasta sequence
wc_from_string <- function(k, text) {
    .Call('zwc_wc_from_string', PACKAGE = 'zwc', k, text)
}

#' Count words in fasta file
#'
#' @param k    Integer expressing word size
#' @param file Fasta filename
wc_from_file <- function(k, file) {
    .Call('zwc_wc_from_file', PACKAGE = 'zwc', k, file)
}

